KTH/devops-course

contributions/presentation/T1G27/README.md
Containerized applications.
Discuss: 
* What are containers?
* How do they work?
* What are they used for?
* Advantages/disadvantages
* Available tools and techonologies
**We want to present at the April 1st lecture.**
=> Presentation proposal: containerized applications (group T1G27)

contributions/presentation/T1G25/README.md
The group number may be preliminary, but it is the one I was assigned to. Read more in #33 .
=> Created presentation task

contributions/presentation/T1G17/README.md, groups/Task1Group.csv
@Anders-E aeri3@kth.se - To group 17
@Oskar-Olofson oskarolo@kth.se - Switched to group 23
=> Change group 17

contributions/presentation/Kartik_Yi-Pei/README.md
Topic: Cross Browser Testing, Selenium Testing, and Mobile Testing.
Name: Kartik Kandavel Mudaliar, Yi-Pei Tu
=> [Presentation] at 25th of March 

contributions/presentation/T1G26/README.md
Fredrik Flovén and Filip Jansson
Flaky tests
=> [Presentation Monday 25th] T1G26

contributions/presentation/T1G9/README.md
First draft of the planned presentation
@yalapeno
=> Group T1G9

contributions/demo/T1-egedda@kth.se+lukassz@kth.se/README.md, contributions/demo/T1G18/README.md, groups/Task1Group.csv
Amplified testing demo.
Relevant comment in issue: 
https://github.com/KTH/devops-course/issues/9#issuecomment-470866599
Emil Gedda, egedda@kth.se
Lukas Szerszen, lukassz@kth.se
=> Task 1 Group 18: Demo

contributions/demo/adamhas_tumanis/Readme.md
Group for demo: Adam Hasselberg and Aigars Tumanis
Topic: TBD
=> Created group for demo

contributions/presentation/Adam_Aigars/README.md
Adam Hasselberg, and Aigars Tumanis
Topic: A/B Testing.
Presentation for Week 3.
=> Presentation for Week 3: A/B Testing.

contributions/presentation/slarse-pornell/README.md
We want to do a presentation on common testing mistakes (focusing on unit testing). 
See the README for more info. 
Partner: @slarse, slarse@kth.se
=> Testing mistakes: Presentation proposal for Monday 25th

contributions/presentation/week3/hrabo-jcelik/README.md
The presentation was placed on the wrong week in regards to topic covered. Moved it to the correct week.
=> Moved presentation proposal to the correct week

contributions/presentation/week2/sjager/README.md
Would like to work alone this week due to travels. Originally in group TIG14.
=> [Presentation] Add week 2 topic

contributions/presentation/Henry-Saha, contributions/presentation/Henry-Saha/Readme.md
Topic: Property-based testing in Java
Members: Henry Luong(Originally group T1G29) and Saha Parumita(Originally group T1G22)
=>  [Presentation Monday 25th]  

contributions/presentation/week2/README.md, contributions/presentation/week2/slarse-pornell/README.md
As discussed with @gluckzhang over e-mail, we have decided to switch topic. Please see the README for additional info.
Me: slarse@kth.se
Partner: pornell@kth @philippaornell 
**Note that I took the liberty of updating the agenda as well**
=> [Presentation week 2] Update proposal (Testing mistakes -> what makes a good test suite)

contributions/presentation/week2/tailp-parumita/Readme.md
What does this PR change ?
Add Google PowerPoint link to Readme.md for preview of the presentation (Read & Comment only)
=> #Doc: add Google PowerPoint link for preview

contributions/competition/README.md
List the binaries to be fuzzed, with instructions about the submissions format
=> update instructions about fuzzing competition

contributions/presentation/week3/krijor/README.md
Registering a topic for a presentation on week 3 about writing testable code
=> Add a presentation suggestion for krijor

contributions/presentation/week4/dadsg-pridell/README.md
Presentation details in the README file.
=> Add dadsg-pridell presentation for week 4

contributions/essay/lukassz-aeri3/README-md, contributions/essay/lukassz-aeri3/README.md
Essay on designing for failure and Chaos Monkey.
Lukas Szerszen, lukassz@kth.se
Anders Eriksson, aeri3@kth.se
=> Essay:Chaos Monkey

contributions/essay/dadsg-parumita/README.md
Description in the readme file.
=> Add dadsg-parumita essay

contributions/essay/slarse/README.md
Hello!
The instructions said we could do a task solo, so I'd like to do that for this essay. I have partners for all other tasks.
I'd like to write an essay on graph databases. I don't know much about them at this time, but I intuitively feel like they are relevant to DevOps due to being schemaless (rapid iteration) and being capable of modeling complex relationships (for example useful to keep track of infrastructure that is constantly in flux).
I will make comparisons with relational databases, and possibly other NoSQL databases (e.g. doc dbs) if there is space left in the essay.
=> Essay: Graph Databases

contributions/essay/sjager/README.md
Forgot to make a PR before starting the work... I hope this topic is fine for week 3 as an essay! If not, any feedback is welcome.
=> [Essay] Week 3

contributions/open/tailp-parumita/Readme.md
We want to try setting up a pipeline with Jenkins(CI, build with maven and test with Junit), Prometheus&Grafana(Issue tracker/monitor) ,Docker(Contanerized deployment) and Kubernetes(Orchestration). Graphical pipeline design will be submitted later.
=> Open project proposal for CI/CD

contributions/open/mudaliar-yptu/README.md
Kindly go through README.md for information
Regards
Kartik, Yi-Pei
=> Proposal for Open Category Task

contributions/presentation/Adam_Aigars/README.md
https://docs.google.com/presentation/d/1K0LQG_78olPQooHIkAnkn3DTVkvFOzkeyNgEAo1O6Mg/edit?usp=sharing
=> Added link for Presentation

contributions/presentation/week3/felixed-erikjo9/README.md
=> Add link to presentation

contributions/demo/saraers-egood-fnorr/README.md, contributions/presentation/week6/ersson-good-norrman/README.md
Members:
* Sara Ersson, saraers@kth.se
* Emma Good, egood@kth.se
* Fredrik Norrman, fnorr@kth.se
Topic suggestion: Docker vs. Vagrant
=> Add topic suggestion

contributions/essay/jakobhol-adibbin/README.md
We want to write about wasm and the future of containers, see readme.
=> Add essay proposal

contributions/essay/mudaliar-tailp/README.md
Hi 
PR for Essay Proposal. 
Topic: People, Cultural Aspects of DevOps
Regards
Kartik, Henry
=> Essay Proposal 

contributions/open/jcroona-slarse/README.md
Hello! Please see the README for our proposal.
=> [Open] GitHub Label Bot

contributions/essay/felixed-erikjo9/README.md
* A comparison between the more *traditional* CI/CD and the more modern pipeline approach.
* Use cases of pipelines.
* Discussion about the advantages/disadvantages of modern pipelines.
* Available technologies and their differences.
=> Add essay proposal README

contributions/demo/asjobom/README.md
I want to set up a CD Pipeline with GitLab's Auto Devops and automatically deploy code to a Kubernetes Cluster on GKE.
The best would be if I can find someone that wants to do this together with me. But If I can't I would like to do it by myself.
If the PR is accepted I will search for someone to do this with via an issue.
=> demo proposal: GitLab Auto Devops and GKE

contributions/presentation/week6/lcjna-nacarter/README.md
Members:
- Louis Nathan, lcjna@kth.se
- Nicole Carter, nacarter@kth.se
Topic: Git at Scale - The World's Largest Repository
=> Add lcjna-nacarter presentation topic (Week 6)

contributions/demo/harisa/README.md
I'd like to demo how one can use statical analysis
and automatic repair to fix some errors without user
input.
=> Demo for Haris Adzemovic (harisa)

contributions/essay/harisa/README.md
I'd like to give an introduction to containers for someone
who has just heard of the concept and would like to learn more.
=> Essay topic for Haris Adzemovic (harisa)

contributions/presentation/week4/dadsg-pridell/README.md
Added presentation link to readme.
=> presentation link

contributions/competition/harisa-lukassz/README.md
Haris Adzemovic (harisa) and Lukas Szerszen (lukassz)
=> harisa and lukassz registering for the competition

contributions/open/jespel-btel/README.md
Hi!
So me and @btellstrom got an idea for an art project related to DevOps when preparing our presentation.
We got the idea to try to visualise flaky test and convey some of the feelings that they create. Our idea is to visualise them with an animation of an ECG that sometimes fails.
Looking forward to discuss this idea with you!
=> Flaky test

contributions/demo/mudaliar-tailp/Readme.md
Please check Readme.md , thanks :) .
=> Doc: Demo proposal

contributions/open/jakobhol-adibbin/README.md
An open proposal. Will this suffice or is more needed?
=> Open proposal

contributions/essay/lcjna/README.md
Why you should be using DevOps.
An example based article on how the tasks you are doing can be automated, a short introduction of DevOps and the history behind its creation with industry examples to back it up.
- Louis Nathan, lcjna@kth.se
=> Add lcjna essay topic

contributions/essay/nacarter/README.md, contributions/essay/ncarter/README.md
Author: Nicole Carter (nacarter@kth.se)
Topic: CI/CD – What this means and how they relate to each other?
Introduction to CI and CD, what they are, how they are used and how interact with each other.
=> Add nacarter essay topic

contributions/open/aeri3-egedda/README.md
Proposal for open assignment with @EmilGedda.
=> Add open proposal for aeri3 and egedda: Fuzzing of JSON parsing libraries

contributions/competition/hrabo-pornell/README.md
Added a group for the grand fuzzing challenge
=> Added challenge group

contributions/essay/hrabo-pornell/README.md
Essay proposal within A/B testing and search based software engineering.
=> Added an essay proposal

contributions/demo/jcroona-slarse/README.md
Hello! Please see the README for our demo proposal.
We are a bit unsure of the topic as it is more on the small scale of building blocks rather than the grand multi-server cloud [many buzzwords omitted] kind of thing that the instructions allude to, but we still think it's an interesting and absolutely fundamental topic for DevOps.
=> [Demo] Add Git plumbing demo proposal

contributions/essay/saraers-miguelmu/README.md
=> Essay proposal: Continuous Testing

contributions/open/jcelik-hrabo/Proposal.md, contributions/open/jcelik-hrabo/README.md
We are finished with our project.
=> [Open] Added project description

contributions/competition/miguelmu-fkollin/README.md, contributions/essay/saraers-miguelmu/README.md
Registration for Miguel Müller and Felix Kollin.
=> Add group for fuzzing competition

contributions/essay/axellaru/README.md
=> essay proposal

contributions/open/tailp-parumita/Readme.md
Hi, please check out [repo](https://github.com/Tailp/CI) :) . Contact me if there are some errors. Thanks .
Changelogs:
* Add detailed readme in this [repo](https://github.com/Tailp/CI) for complete setup of the pipeline
* Add 2 tutorial videos for explaining in details how to set up on-demand slaves and also how to easy deploy as Jenkins master to K8s along with readme in this [repo](https://github.com/Tailp/CI)
=> [Open task] Final submission CI/CD pipeline

contributions/open/erikjo9/README.md
Added the url to the prototype.
=> Add submission URL

contributions/demo/gusgun-jakobhol/README.md
Added a link to our screencast.
=> Demo screencast

contributions/demo/erikjo9/README.md
Add the url to the screencast of the demo
=> Add screencast URL

contributions/demo/asjobom-fkollin/README.md
We wrote a more detailed description of our demo and added the screencast.
=> Demo submission: Gitlab Auto DevOps and Pipeline Dashboard

announcement/README.md, contributions/demo/egedda-lukassz/README.md
=> Demo: alter topic and add description

contributions/competition/README.md
This is a first version of the fuzzing competition instructions.
=> Grand Fuzzing Challenge 2020

contributions/essay/dstevens/README.md
David Stevens (dstevens@kth.se)
Automated testing in video games.
Testing in video games is notoriously difficult, as it contains all the difficulties of testing GUIs while also adding a near infinite state space in which bugs could occur. It would be interesting to dive into the specific strategies that are employed.
- What makes testing video games different?
- Strategy
- Unit tests
- Testing logic components
- Integration tests
- Simulated playthroughs
- Comparing video feed to pre-defined output
- Other strategies I have yet to discover
- Conclusions
=> Add initial essay proposal

contributions/presentation/week2/applelid-kasperli/README.md
Pull request for Kasper Liu and Gunnar Applelid
=> Presentation Topic for week 2

contributions/demo/tommysam-stinalan/README.md
**Demo Proposal**
**Members**
Tommy Samuelsson (tommysam@kth.se)
Stina Långström (stinalan@kth.se)
**Topic**
Data corruption
The idéa is to securly use fetched data in applications. So the application in it self can relay on that data it will use in different components won't crash the application. If a data set is demed corrupted it will discard it then notfiy ennd user that data with ID:# was not renderd. (Notification can be via slack, mail or similar).
**Demo**
Two live pages the receive the same data. But the one not using the "data corruption handler" will crash when they receive the corrupted data set. 
The demo could be interactive by having a input field(s) for data. Allowing the demo-viewer to try to crash the site's. (Hopefully only one will crash)
=> Add initial demo proposal

contributions/presentation/week3/uggelberg-west/README.md
Pull request from Balthazar West and Richard Uggelberg.
=> Presentation topic for week 3: ATDD vs TDD

contributions/presentation/week3/sevinc-rezkalla/README.md
We will look through the topic and pick up a detailed question/topic in CI/CD. Our current question is: how do you test the tester? Testing the CI pipeline.
Group Members:
* Cevat Aykan Sevinc sevinc@kth.se
* George Rezkalla rezkalla@kth.se
=> Presentation Topic for week 3: Testing of CI pipeline

contributions/presentation/week3/jonasjo5-marcusew/README.md
Jonas Johansson, jonasjo5@kth.se Github username: jonasjohansson8908
Marcus Jonsson Ewerbring, marcusew@kth.se Github username: Marcus9512
A comparison that covers:
- How do they work, what differs?
- Different features?
- Design differences, why?
- How are they integrated with git? (Maybe setup an example)
- Pros and cons.
=> Presentation topic for week 3, Travis vs Jenkins, a comparison of two popular CI tools

contributions/tutorial/sunneg-klaraes/README.md
Copy of README:
*Team members: Christina Sunnegårdh (sunneg@kth.se), Klara Eserstam (klaraes@kth.se)*
**Interactive task:** Dockerizing a client and a server (node.js/react) in an application  separately (using docker compose).
We feel like there is no current tutorial that gives a good background on docker as well as also shows how to dockerize a client/server application and outlines when/why one would do that. We aim to provide a complete guide for this for someone who is new to Docker.
- Background
- Overall info, what docker is/what it can be used for
- Information about the task (when/why it is preferable, advantages etc, “case”)
- Tutorial part
- Explaining commands used
- Execute the commands on Katacoda
- The TA can successful execute all the commands of the tutorial (mandatory) …
=> Tutorial proposal Docker (sunneg-klaraes)

contributions/tutorial/rosquis-shapour/README.md
**Members of the group:** 
Christine Rosquist (rosquis@kth.se, Github: christinerosquist) and Shapour Jahanshahi (shapour@kth.se, Github: shappe)
**Topic:**
Cloud-based error monitoring using Sentry.io. 
We would like to learn more about monitoring and error tracking. Sentry.io seems like a beginner-friendly alternative and we want to know more about how to use it in our own applications. 
- How to set up the platform (including installation and setup)
- How to use the platform (the dashboard etc) in your own programs 
We will provide a background with information regarding monitoring and error tracking, but also explain the main princples of Sentry.io. We will also provide a step-by-step tutorial showing the setup and how to use the platform, in a way that is easy to follow. The tutorial …
=> Tutorial proposal: Sentry.io

contributions/tutorial/pbroberg-joarr/README.md
**Team members:**
Pontus Broberg (pbroberg@kth.se) & Joar Rutqvist (joarr@kth.se)
**Topic:**
Automated testing using Lambdatest.
Automated testing is really useful when working in larger application projects. We would like to
learn more about the process of creating an automated testing environment and while doing so, also creating an
easy to follow tutorial on how one can get started and use Lambdatest for their automated testing.
Our tutorial aim to show how to:
- Setup an automated testing environment with Lambdatest
- Add and remove tests
- Navigation and understanding of the Lambdatest UI
- The TA can successful execute all the commands of the tutorial (mandatory)
- The tutorial gives enough background
- The tutorial is easy to follow
- The tutorial contains fun facts or easter eggs
=> Tutorial: Lambdatest

contributions/essay/dingli/README.md, contributions/tutorial/dingli-akshay/README.md
- Dingli Mao dingli@kth.se
- Akshay Sinha akshays@kth.se
Gocd is a free and open-source Continuous Integration and Continuous Delivery system. We will provide all essential steps regarding install and set up Gocd server. In addition, we will examine and explain most functions of Gocd.
=> The proposal for Tutorial

contributions/presentation/week2/madon-vals/README.md
Hi,
@valsen and I want to make a presentation next week around the "bus factor". 
We also want to ask the TA for some guidance. We found three papers about computing the "bus factor" for git projects. If we go into details it can make a full presentation. But we are not sure if it is the most interesting to only stick to that... We could extend to gender equality and diversity in git repo contributors, ask the open question "what is the profile of an open source contributor?" or else look into how we can assess the health of a repo by looking at the git history.
What's your views about that?
=> Presentation week2 bus factor

README-2019.md, contributions/tutorial/asratyan-dautaras/README.md
Students:
Albert Asratyan asratyan@kth.se @Goradux
Justas Dautaras dautaras@kth.se @sonderangebot10
Topic: Asp.net core 3.1 microservice deplyoment to openshift
We would like to make a tutorial for deploying the newest version of asp.net microservice to openshift. 
We've not had any experience with this and we couldn't find any topics regarding this version of asp.net, so we though this would be a useful tutorial.
=> Tutorial On Openshift ASP 3.1 Deployment

contributions/presentation/week4/jadlers-dingli/README.md, contributions/presentation/week4/jadlers/README.md
I'm planning on giving a presentation on Ansible and how it can be used to manage configuration in week 4. If someone else is interested in the same topic let me know, we could potentially collaborate.
=> Presentation: Using Ansible

contributions/tutorial/bratfors-kasperli/README.md
- Robin Bråtfors, bratfors@kth.se
- Kasper Liu, kasperli@kth.se
A tutorial that teaches the reader how to install and setup TeamCity from scratch for a gradle project on GitHub. The tutorial will have some screen captures and should be easy to understand for anyone with experience in GitHub, but not necessarily with continuous integration.
=> Tutorial proposal: TeamCity

contributions/tutorial/rhodin-kotsias/README.md
**Team Members:** Sandro Lockwall Rhodin (<sandror@kth.se>) and Aristotelis Kotsias (<kotsias@kth.se>)
**Description of the Topic:** 
BuildBot is a CI-tool which can be used to automate a number of tasks such as testing and compiling. We intend to produce a tutorial on how to perform installation setup for BuildBot in a Docker environment utilising KataCoda and then also how to setup a functioning GitHub integration. If we for whatever reason cannot get the KataCoda environment working properly we will instead produce a tutorial for how to utilise BuildBot locally (paired with GitHub). The tutorial is to either use GIFs or Video content to expand upon (and hopefully simplify) the aid one might otherwise find in the documentation of BuildBot. 
**Structure of Tutorial:**
1. Information …
=> Tutorial Proposal: BuildBot

contributions/essay/dleon-nicolaih/README.md
Diego Leon (dleon@kth.se)
Nicolai Hellesnes (nicolaih@kth.se)
Docker and its scalability
Scalability is an important factor when developing an application. In this essay we will discuss the scalability that Docker provides.
- Scalability
- Docker
- Containers
- Scalability
- Conclusions
=> Proposal for Essay: Scalability comparison: Docker Swarm vs K8s

contributions/presentation/week3/htchan-lhlchoy/README.md
----
Speakers:
Ho Ting Chan (htchan@kth.se)
Louise Hui Ling Choy (lhlchoy@kth.se)
----
Topic: Is Docker going to replace VMware?
1. Background on why we choose this topic
2. Introduction to Docker (containerization) and VMWare (virtualization)
3. Comparison
4. Future speculation
=> init presentation proposal

README.md, contributions/tutorial/varkalys-vplohse/README.md
Mindaugas Varkalys varkalys@kth.se @MindaugasVarkalys
Vincent Lohse vplohse@kth.se @olapiv
Building Docker server for multiple web applications
We were trying to host our web applications using Docker Compose on Microsoft Azure, but it caused a lot of hassle and in the end it didn't work. So we decided to build our own Docker server which would allow easily deploy and host multiple Docker web server applications on multiple domains. As we searched, there is no such tutorial, so we will create one.
- Setting up Docker and Docker Compose
- Setting up reverse proxy using Nginx
- Issuing and automatically renewing SSL certificates
=> Tutorial: Building Docker server for multiple web applications

contributions-2019/presentation/week4/jii-stinalan/README.md
Presentation proposal for Johanna Iivanainen (jii@kth.se) and Stina Långström (stinalan@kth.se)
=> Presentation proposal: How to build a DevOps culture

contributions/presentation/week2/javierro-sasig/README.md
Sigrún Sigurdardottir (sasig@kth.se)
Javier Ron Arteaga (javierro@kth.se)
Docker: Security features
In this presentation, we will describe the security features that Docker implements to mitigate attacks on either the host machines or containers
Knowing how to run secure containerized applications is an important skill given the widespread use of these today. In this presentation we will try to explain the basics of it along with and some examples of successful attacks.
- Attack surfaces
- Containers
- Container breakout
- Malicious image loading 
- Docker daemon
- Mitigation strategies
- Namespaces
- Control groups
- Docker daemon considerations
- Linux Kernel Capabilities
=> Presentation proposal: Docker security features

contributions/presentation/week4/xmas92-Callet91-Volminger/README.md
We plan to do a presentation with regards to testing in DevOps, probably something with related to regression. Will do more research and have a more specific topic by the end of the week.
Alexander Volminger (alevol@kth.se)
Github username: Volminger
Axel Boldt-Christmas(axelbc@kth.se)
Github username: xmas92
Carl Jensen (calle.jensen@outlook.com)
Github username: Callet91
WIP
Testing in DevOps chain. Focus on something with regression testing.
=> Presentation week4: Test Amplification in DevOps

contributions/essay/madon/README.md
Hi, 
I am very interested by the link between ICT and sustainability. I already took different courses, I did an internship and I am also planning to do a PhD on the topic.
I was wondering if I could take the opportunity in this course to look for the links between DevOps and sustainable software? I will wait until Tuesday's lecture to have a better overview of DevOps to precise my subject. If you have any idea they are of course welcome.
And if you think I am off-topic for this course it is perfectly fine, I can totally work on something else.
Thanks!
=> draft PR for essay on sustainable software

contributions/tutorial/hiteshs-eyueltb-avijit/README.md
Describing & implementing features of Azure DevOps and explaining how it provide one stop environment for implementation of CI/CD pipeline with ease.
=> Tutorial Proposal- Azure DevOps Pipeline

contributions/demo/pojans-avijit-akhsays/README.md
So basically we are going to define a liveness probe for a pod; The web server running on the pod is coded in such way that we can break it with certain input and thus failing the liveness probe.
=> Demo Proposal: Kubernetes self-healing

contributions/presentation/week2/javierro-sasig/README.md
Presentation slides link for our Docker & security presentation
=> Week 2 Presesntation: Slides

contributions/tutorial/jii-louiseze/README.md
After discussing with @gluckzhang in the comments of our old PR #377 , we decide to change the topic of our tutorial. Here is our new tutorial proposal.
=> Tutorial proposal: Github Apps and Actions

contributions/essay/emetha/README.md
Initial Draft of Essay Structure:
- Introduction  
- What is Configuration Management?
- Configuration Process
- Configuration Management in DevOps
- Source Code Repository
- Artifact Repository
- Configuration Management Database
- Comparison of Salt and Ansible
- Salt
- What is Salt?
- Salt Drawbacks
- Ansible
- What is Ansible?
- Ansible Drawbacks
- Conclusion
Emelie Tham (etham@kth.se)  
1. https://www.pluralsight.com/guides/role-of-configuration-management-in-devops
2. https://www.saltstack.com/blog/beyond-configuration-management/
3. https://www.ansible.com/use-cases/configuration-management
4. https://ieeexplore.ieee.org/abstract/document/7490666
5. https://lsi.vc.ehu.eus/pablogn/docencia/antiguos%20AS/AS1819AS/Act5%20infrastructure-as-code,%20Configuration%20Management/Terraform%20 …
=> Essay proposal: An introduction to Configuration Management Tools Salt and Ansible

contributions/essay/README.md
Hi @monperrus , @bbaudry , @SophieHYe , @cesarsotovalero ,
The requirements for passing / passing with distinction for essay is missing (#415). This is a pull request to fix it.
=> fix: essay grading criteria about pass with distinction

contributions/presentation/week4/rosquis-shapour/README.md
**Members of the group:** 
Christine Rosquist (rosquis@kth.se, Github: christinerosquist) and Shapour Jahanshahi (shapour@kth.se, Github: shappe)
**Topic:**
A/B Testing in DevOps. 
We would like to learn more about A/B Testing since it seems like an interesting topic that is relevant in DevOps. 
- Background/Introduction to A/B Testing, what it is in general
- Why A/B Testing is relevant in DevOps
- Include a concrete technical example: How Netflix uses A/B Testing 
- Reflections and take-home messages
=> Presentation proposal week 4: A/B Testing

contributions/tutorial/chikafa-mjza/README.md
…ting Microservices in Spring Boot Applications: Tools and Techniques (Week 4)
=> Tutorial Proposal: Testing Microservices in Spring Boot Applications: Tools and Techniques (Week 4)

contributions/competition/tommysam-stinalan/README.md
**Members**
Tommy Samuelsson (tommysam@kth.se)
Stina Långström (stinalan@kth.se)
=> Add Grand Fuzzing Challenge 2020!

contributions/demo/Callet91-xmas92/README.md
Carl Jensen (carljen@kth.se) Github username: Callet91
Axel Boldt-Christmas (axelbc@kth.se) Github username: xmas92
CI/CD pipeline for embedded devices using PlatformIO and Jenkins
Demo of implementing PlatformIO in a CI pipeline with Jenkins for testing scripts intended to run on embedded eval boards. If possible we would like to integrate CD to our pipeline. 
When developing for embedded systems, tests that relate to the actual hardware are often done manually on a dedicated testrigg. This is time consuming and often creates a bottleneck in the workflow since only a small team can work on the testrigg one at a time. Automation of physical tests could hopefully reduce the time spent in the lab and to verify the code under test. 
Jenkins server for handling the CI flow.
Using PlatformIO …
=> Demo proposal: CI/CD pipeline for embedded devices using PlatformIO and Jenkins

contributions/demo/javierro-hiteshs/README.md
This PR (https://github.com/KTH/devops-course/pull/370) was accidentally closed, so I am reopening it.
Hitesh Sharma (hiteshs@kth.se) Javier Ron Arteaga (javierro@kth.se)
Kubernetes Automation:
We will make a demonstration of how the Kubernetes autoscale feature works in improving app availability.
We will simulate a live setup, generate traffic and provide visualization to better understad the app's behavior.
=> Proposal for demo: Autoscaling for high availability using Kubernetes

contributions/open-source/README.md
These quality criteria will filter out spurious projects from the students' radar.
=> Add project selection criteria

contributions/demo/javierro-hiteshs/README.md, contributions/open-source/javierro-sasig/README.md
Sigrún Sigurðardóttir (sasig@kth.se)
Javier Ron Arteaga (javierro@kth.se)
Automation through bots is currently a very popular tool that fits well in the DevOps sphere. 
This issue is posted in the Imgbot repository: 
https://github.com/dabutvin/Imgbot/issues/352
We might be just testing the waters here. We would like to know if the scope of solving this issue is appropriate for the course, and also since the grading criteria is a bit subjective, if it is considered hard enough to get a P+.
=> Proposal: Open-source contribution

contributions/demo/dleon-nicolaih/README.md
Diego Leon (dleon@kth.se)
Nicolai Hellesnes (nicolaih@kth.se)
Deploying a container based application with Kubernetes as the orchestration platform, with automated testing using Jenkins.
A backend & frontend web application using containers and kubernetes. We will use Jenkins for automated tests and deployments.
=> Demo Proposal: Deploying a container based application with Kubernetes as the orchestration platform, with automated testing using Jenkins.

README-2019.md, contributions/essay/asratyan-dautaras/README.md
The description is copied from the README.md so you don't have to check it out:
---
- Albert Asratyan @Goradux <asratyan@kth.se>
- Justas Dautaras @sonderangebot10 <dautaras@kth.se>
- Sigrún Arna Sigurðardóttir @s1grun <sasig@kth.se>
Amazon Web Services has become one of the staples of any modern platform development. It would be interesting to take a deeper look into how AWS may influence use of DevOps practices, even if it is not obvious on the surface.
The focus will be on:
- Benefits of AWS compared to a clasically deployed server setup
- What development approaches AWS encourages
- Draw a parallel between these AWS approaches and the core ideas of DevOps development
- Give concrete examples of what AWS services correspond to what DevOps practices
=> Essay Proposal (AWS Influence on DevOps)

contributions/presentation/week4/paulher-hmellin/README.md
Paul Löwenström: paulher@kth.se
Henrik Mellin: hmellin@kth.se
Topic: Monitoring in DevOps
We would like to do a presentation on the monitoring phase in DevOps cycle
* what it is
* different ways of monitoring and their pros and cons.
* give an example using an existing service
=> Presentation proposal, week4: Monitoring. tracing. observability in DevOps

contributions/essay/marcusew/README.md
Marcus Jonsson Ewerbring (marcusew@kth.se)
Github username: Marcus9512
Different ways of improving DevOps with Machine learning.
My proposal is to write an essay on how you could use machine learning to improve DevOps. 
I did some research and couldn't find so many solutions related to devops. I therefore propose an essay about gathering ideas on how machine learning can improve this area.
Examples:
* Pattern recognition in server logs, to recognise anomalies etc.
* Predicting application/server failure
* Optimising software testing with machine learning.
When I have discovered the areas that could be improved by machine learning, I want to discuss which machine learning method/methods is suitable to solve the problem/problems.
* Introduction
* What is ML, (also present relevant methods) …
=> Essay proposal: Different ways of improving DevOps with Machine learning

contributions/tutorial/mhud-rezkalla/README.md
* Helal Uddin - mhud@kth.se @sujon2100
* George Rezkalla - rezkalla@kth.se @georgewbar
VSTS is a team foundation server in a cloud. It's been around 13 years to help teams, managers, software developers to manage there developing efforts. It helps with source code, project plan, automated build, automated deploy, testing, bug tracking as well as to manage all kinds of developing stuff. With VSTS, it is possible to get all of these services but in a cloud. Because of that no need to worry about running or backing it up as Microsoft is dealing it on the behind in the cloud. It is possible to have the same features on the on-premise version of TFS. Azure DevOps Is the new version of VSTS. Same functionality but more features. As it has been observed that Microsoft has changed a lot from it's …
=> Tutorial proposal - Implementing Azure DevOps 

contributions/presentation/week5/davidjo2-johvh/README.md
* David Johansson (davidjo2@kth.se)
* Johan von Hacht (johvh@kth.se)
Comparing two different deployment strategies in the form of Blue/Green deployment and Canary deployment. We find the topic interesting considering that deployment is a key part of DevOps and these two strategies are used within the industry.
* Introduction
* Describing Green/Blue deployment
* How it works  
* Describing Canary deployment
* How it works
* Comparing the two different strategies
* Pros/cons
* Take home message
=> Presentation week 5: Deployment Strategies

contributions/presentation/week5/sunneg-klaraes/README.md
Team members: Christina Sunnegårdh (sunneg@kth.se), Klara Eserstam (klaraes@kth.se)
Copied from readme:
DevOps teams - roles, responsibilities and habits
To successfully adopt DevOps into your organization, it's important to have teams that are onboard and who work well together. Culture is a big part of DevOps, and we think it's important to learn about these things as well.
- Roles and responsibilities in DevOps teams
- How large companies organize DevOps teams
- If we find anyone: personal experience from a DevOps team in tech Stockholm
=> Presentation proposal: DevOps teams - roles, responsibilities and habits

contributions/demo/adambjo-mhud/README.md
Helal Uddin (mhud@kth.se)
Demo of virtual network peering in Microsoft Azure.
According to Microsoft, Virtual network peering enables a seamless connection between Azure virtual networks. By using both private and global virtual network peering, it is possible to route traffic with low-latency, high-bandwidth. Virtual machines can communicate with other virtual machines by using VNP. This communication process is connected with other resources such as Azure subscription, Azure Active Directory(AAD) in the Azure portal. As this communication is private, there is no necessity to implement encryption. In this demo, we will present how to create multiple virtual machines,  virtual network peering in the Azure portal.
=> Demo proposal: Virtual network peering in Microsoft Azure

contributions/feedback-planning.md
Me and @johannaii want some feedback on our tutorial.
=> Register for feedback

contributions/presentation/week4/hiteshs/README.md
Presentation by Hitesh Sharma (hiteshs@kth.se)
(A) - Intro. on what is DevOps?
As We know... 1 liner.
- Different tools and technologies used in DevOps and discussion on them
- Problem: What to learn?
Solution: ...
(B) Technical discussion about Jenkins Pipeline
Content I will include as per your suggestions. I have to prepare it. It will not include docker to avoid any complexity but I will try to cover pipelines of Jenkins in depth.
(C) Conclusion and Questions
NOTE: I am targetting for distinction and will try to fulfill the majority of requirements. 
Items listed above is just proposal and may be added or deleted in the final version depending on their relevance.
All the discussions will be in line with my industry experience and on real-world facts.
=> Presentation Proposal Week 4- DevOps in an Industry Implementation

contributions/essay/louiseze-stinalan/README.md
Louise Zetterlund (louiseze@kth.se)
Stina Långström (stinalan@kth.se)
Code coverage.
Code coverage is a way to see how much of the code that is covered when the tests run. By having a high code coverage your program has a lower risk of having undetected bugs. We would like to write an essay on the background to code coverage and the different ways of using this when developing softwares.
- What is code coverage?
- How is this correlated to the amount of bugs in your code/what does science say about code coverage?
- How can a developer use the concept of code covering when developing software?
- Are there any tools to help with code covering?
- Conclusions
=> essay proposal: code coverage

contributions/tutorial/marcusew-dleon/README.md
Marcus Jonsson Ewerbring (marcusew@kth.se)
Github username: Marcus9512
Diego Leon (dleon@kth.se)
Github username: dieflo4711
An introduction on how to use unit testing, regression testing and code coverage with IntelliJ. 
Testing is an important software engineering practice and necessary to keep the state of quality of the software product or service under test. We will focus on Unit testing and regression testing. Code coverage provides critical information about where to focus testing, and is an important metric in Software testing.
We are planning to publish this on medium, katacoda or some forum that fits the tutorial.
* Introduction
* Why should we test our program
* What is unit-testing and why is it important
* What is regression testing 
* What is code coverage
* Why we (the …
=> Tutorial Proposal: An introduction on how to use unit testing, regression testing and code coverage with IntelliJ 

contributions/tutorial/hellesnes-madon/README.md
Hi!
@nicolai-h and myself want to make a tutorial about fuzzing. Here is our proposal, which will be refined after trying the tool and following existing tutorials.
If you have any suggestion or question, do not hesitate!
=> Tutorial proposal: fuzzing with Radamsa

contributions/tutorial/perfah-joarek/README.md
1. Per Fahlander (perfah@kth.se)
2. Joar Ekelund (joarek@kth.se)
Creating a Katacoda-tutorial on how to put a game in a Docker-container. The tutorial would be named “Dockerizing your Favorite Game”.
We are considering the game https://github.com/alexdantas/nsnake to demonstrate that it works.
Games usually have a lot of dependencies and perhaps it could be interesting to have a container that always can launch a game.
The project would involve the following:
- Containerization
=> Tutorial proposal: Dockerizing your Favorite Game

contributions/feedback-planning.md
Feedback wanted for [#507](https://github.com/KTH/devops-course/pull/507)
=> Feedback wanted: Demo #507

contributions/essay/rhodin-kotsias/README.md
(Updated) The essay will give an insight into Maven as a DevOps tool. The main points that will be addressed in the essay are:
1. Introduction to Build Tools
2. Relation to DevOps
3. Definition of Build dependencies
4. Structure of the Maven Build dependencies
5. The Maven repository.
6. Concluding points
=> essay proposal: Maven and its handling of build dependencies

contributions/demo/louiseze-jii/README.md
Louise Zetterlund (louiseze@kth.se)
Johanna Iivanainen (jii@kth.se)
Demo of mutation testing with [Pitest](https://pitest.org/) and the IDE IntelliJ.
We want to make a video demo on the mutation testing system PIT. We will demonstrate how you install PIT, integrate it to the IDE IntelliJ and let PIT run the unit tests in a Java project. We will also upload the Java project to Github, so that people can use that one for testing their own installation and integration of PIT.
- Short introduction to Pitest
- Demo on how to implement it
- Show how to use it on code
=> Demo proposal: Pitest.org

contributions/tutorial/rezkalla/README.md
George Rezkalla - rezkalla@kth.se @georgewbar
This tutorial will be about how to use Declarative pipelines and how to use Jenkins user interface to build a pipeline to compile a demo maven java app and run the unit tests whenever the code is pushed to a repo. The idea is to show two different ways of doing the same thing.
I will try using katacoda to make this tutorial. However, if there are some issues regarding using katacoda, i will demostrate how to install jenkins locally on a computer, and do the tutorial locally.
=> add tutorial proposal

contributions/presentation/week6/jovi-sandror/README.md
Johan Vikström <jovi@kth.se> and Sandro Lockwall Rhodin <sandror@kth.se>
The field of monitoring is a central aspect of the DevOps work loop. Within this field of observation of a various amount of data, there exists the subfield of tracing. Tracing being the act of following requests as they travel through a multitude of applications, detailing if and where errors occur. In particular tracing is useful for applications utilising more than one service.
We would be interested in holding a presentation specifically about the tracing aspect of the monitoring field in the DevOps loop. Our presentation would cover the following:
* Explain why it's more difficult to observe a distributed system than a single-host system.
* Explain roughly what distributed tracing is and what we want to achieve …
=> Presentation proposal week6: Tracing

contributions/presentation/week5/tommysam-louiseze/README.md
Tommy Samuelsson (tommysam@kth.se)
Louise Zetterlund (louiseze@kth.se)
Agile software development
This presentation will focus on Scrum techniques and the different tools you can use to set up and perform a proper sprint.
- Background to SCRUM
- Importance to DevOps
- How to plan a sprint
- How to work during a sprint with examples of testing
=> Add Presentation Proposal Agile software development

contributions/demo/README.md
=> update grading criteria for demo

contributions/presentation/presentationLink
https://www.youtube.com/watch?v=PHpJ41uhty4
Presentation of week4 by hiteshs
=> Submission of presentation link

contributions/essay/jonasjo5/README.md
Jonas Johansson, jonasjo5@kth.se
Github username: jonasjohansson8908
I want to learn more about containers and how they differ from VMs. 
More specifically, I would like to cover how they can be used in a DevOps context and the
benefits and drawbacks of each solution.
- Introduction
- Background
- What is a VM, how does it work?
- What is a container?
- Images
- Differences between containers and VMs.
- Benefits and drawbacks, when to use which solution?
- A specific example covering two common tools and how they can be used in DevOps. (Will choose a specific tool of each after researching)
- Conclusions
=> Essay suggestion: VMs, Containers and their relationship to DevOps

contributions/essay/carljen-alevol/README.md
Alexander Volminger @Volminger alevol@kth.se  
Carl Jensen @Callet91 carljen@kth.se
Docker is the most popular way of running containers but people have raised safety concerns with Docker. An alternative to Docker is Podman, which is a deamonless way of running your containers. We want to investigate the benefits of running containerized applications using a daemonless container platform and explore if these benefits outweigh the downsides of running it in this fashion.
A short selection of relevant material: 
https://cloudnweb.dev/2019/10/heres-why-podman-is-more-secured-than-docker-devsecops/ 
https://cloudnweb.dev/2019/06/replacing-docker-with-podman-power-of-podman/
https://podman.io/ 
https://www.docker.com/why-docker
https://github.com/containers/buildah …
=> Essay proposal: Running containers in a daemonless fashion, is it worth it?

contributions/tutorial/marcusew-dleon/README.md
Marcus Jonsson Ewerbring (marcusew@kth.se)
Github username: Marcus9512
Diego Leon (dleon@kth.se)
Github username: dieflo4711
An introduction on how to use unit testing, regression testing and code coverage with IntelliJ. 
Testing is an important software engineering practice and necessary to keep the state of quality of the software product or service under test. We will focus on Unit testing and regression testing. Code coverage provides critical information about where to focus testing, and is an important metric in Software testing.
We are planning to publish this on medium, katacoda or some forum that fits the tutorial.
* Introduction
* Why should we test our program
* What is unit-testing and why is it important
* What is regression testing 
* What is code coverage
* Why we (the …
=> Finished: [Tutorial] An introduction to unit test, regression test and code coverage with IntelliJ 

contributions/feedback-planning.md
Hello, we would like to have feedback on PR #540
=> Feedback wanted for PR #540, Tutorial

contributions/demo/jadlers/README.md
I will add monitoring of stats like response time and status for requests sent
to my API. The monitoring will be visualised with something like grafana or
prometheus. This will allow me to create a better understanding of how the API
is used. I will also add persistent logs in order to make it easier to trace
errors.
The demo will show how the data monitored is captured and also how it's
displayed.
=> Demo: Adding monitoring to an API for a personal website

contributions/competition/adambjo/README.md
=> Competition registration

contributions/demo/jonasjo5-marcusew/README.md
Jonas Johansson, jonasjo5@kth.se
Github id: jonasjohansson8908
Marcus Jonsson Ewerbring, marcusew@kth.se
Github id: Marcus9512
We want to demonstrate how to integrate and use continuous delivery and continuous deployment with CircleCI. 
We will provide a GitHub repository together with our screencast. The viewer can fork the repo and will be provided two branches, one with a complete implementation and one unfinished setup.
We will show how new features can be delivered into an existing app.
We will highlight some features that make CircleCI a strong competitor within continuous deployment and some features that facilitate the migration from Jenkins to CircleCI. 
Hopefully (if we manage to pull it off), we will show some examples of integration with Docker and Kubernetes.
=> Demo proposal - Continous development, delivery, and pipelines with CircleCI

contributions/tutorial/ruwaid-davidjo2/README.md, contributions/tutorial/ruwaid/README.md
Ruwaid Louis - ruwaid@kth.se @ruwaid4 </br>
David Johansson - davidjo2@kth.se @SoFoDa
This tutorial will be about how to use the tool Rodin to model a simple system in Event B. The tutorial will also go through the proof obligations, some lesser known operators and refining. How to install Rodin will also be included in the tutorial.
I haven't even convinced myself entirely that modelling belongs in devops. But i think it can be a great tool to assure quality and keep better track of a project. Here are however three sources which implicates that modelling can belong in devops:</br>
https://www.researchgate.net/publication/299911373_DevOps_meets_formal_modelling_in_high-criticality_complex_systems </br>
https://devops.com/modeling-place-devops/ </br> …
=> Initial tutorial proposal - Rodin: Modelling with Event B

contributions/covid19/bwest-rug/README.md
My group is near a final submission so the project has changed slightly and some things have become more clear. The proposal now reflects these things. Most importantly the last feature has been replaced.
=> Update COVID-19 project proposal

contributions/open-source/hmellin-paulher/README.md
Paul Löwenström: paulher@kth.se
Henrik Mellin: hmellin@kth.se
Zerocode introduction video
We would like to contribute to an open-source project, namely https://github.com/authorjapps/zerocode.
The project has an issue where they want a short video demonstration of Zerocode. 
We think this contribution would be appreciated as the issue is labeled as _help wanted_.
This contribution could also improve the documentation of the project in a way, as it will 
help new users get familiar to Zerocode. 
The issue can be found here:
https://github.com/authorjapps/zerocode/issues/231
Since this Zerocode is about API automation and testing frameworks, 
we think this contribution falls under this topic:
https://github.com/KTH/devops-course/issues/9
=> Open-source contribution proposal: Zerocode introduction video

contributions/open-source/perfah-applelid/README.md
Add a link to the repo where the progress is made for our open-source project.
=> Add link to the repo

contributions/covid19/tommysam-jii/COVID19_COURSE_INFO.md, contributions/feedback-planning.md
In this PR, you will find our submission for the COVID-19 assignment. The link to the mobile app is included in the report.
=> Final submission: COVID-19 assignment

contributions/essay/johvh/README.md
Johan von Hacht (johvh@kth.se)
Introduction to load balancers.
Load balancing servers is a crucial part of any application expected to handle large amounts of traffic/load. It would, therefore, be interesting to investigate different load balancing techniques.
- Introduction
- What is a load balancer
- Why is it used
- Different types of load balancers
- Hardware
- Software
- Virtual
- Different load balancing algorithms
- Round robin
- Least connections
- Least time
- etc.
- Conclusions
https://avinetworks.com/what-is-load-balancing/
https://www.nginx.com/resources/glossary/load-balancing/
https://www.dnsstuff.com/what-is-server-load-balancing
=> Essay proposal: Introduction to load balancers

contributions/covid19/perfah-joarek/README.md
Per Fahlander (perfah@kth.se)
Joar Ekelund (joarek@kth.se)
Write a webserver in Python that fetches and presents [official CSV-data from DGG (Myndigheten för digital förvaltning)](https://www.dataportal.se/sv/datasets/525_1424/antal-fall-av-covid-19-i-sverige-per-dag-och-region) on the number of COVID-19 cases per Swedish region/county. This data would be presented on a website with a graph plotting the development of newly confirmed cases in any region (with available statistics).
The official website from Folkhälsomyndigheten does not show newly confirmed cases per region/county in graph-form. It would be a nice addition to be able to see a plot on the development in specific regions since it is hard to see trends from data sheets.
We will use the following DevOps-related practices in …
=> Covid-19 proposal: Covid-19 Cases by Counties

contributions/demo/jovi-sandror-felixlut/proposal.md
We would like to demo the topic specified in the proposal!
=> Demo Proposal: Load balancing gRPC Remote Procedure Calls in Kubernetes

contributions/essay/varkalys-vplohse/README.md
We finished the essay. This is a link to it:
https://medium.com/@mindaugasvarkalys/nodejs-mariadb-galera-is-it-a-right-choice-for-scalable-ecommerce-api-9288aa682145?sk=53ace0bee7ee9db4d83d3f78c6dc926d
=> Add link of finished essay

contributions/presentation/week6/perfah-settlin/README.md
Per Fahlander (perfah@kth.se)
Johan Settlin (settlin@kth.se)
A rough introduction and overview of the discipline known as “Chaos Engineering”. What is the point of it and how is it used?
Chaos Engineering helps to contribute to the goal of continuous testing in the DevOps toolchain.
Chaos Engineering
What is it / motivation? (fallacies of distributed systems, etc...)
Why break things on purpose?
Methodology
Companies that uses Chaos Engineering
Examples
Chaos monkey
Results
=> Presentation proposal: Chaos Engineering (week 6)

contributions/essay/pojans-sraa/README.md
We want to learn more about continuous testing and therefore we chose to write an essay about this subject. 
| Name | Email |
| ------ | ------ |
| Pojan Shahrivar | pojans@kth.se |
| Sashikanth Raavikanti | sraa@kth.se |
- What is continuous testing?
- Benefits
- Methods
- Role in Devops
- Frameworks & Tools
- Conclusion
=> Essay proposal: What is Continuous testing?

contributions/competition/cwing/README.md, contributions/tutorial/bwest-cwing/README.md
* Balthazar West, bwest@kth.se, Github: balwes
* Christer Winge, cwing@kth.se, Github: cwinge
We propose to create a tutorial that showcase a possible toolchain of helpful tools that would assist in making sure the application is in a desired state at the end of development.
This would include tools that handle the following key points
* code analysis
* testing
* obfuscation (and minimization)
* compilation
With a completed tutorial, one should be able to chain these tools together, making it a very effective process that is essentially automated.
=> Tutorial Proposal: Python toolchain for deploying a release build

contributions/tutorial/alevol-keivanm/READEME.md
**Team members:**
- Keivan Matinzadeh keivanm@kth.se @keivanm
- Alexander Volminger alevol@kth.se @Volminger
**Topic:**
Github Actions: CI for Java with Maven
Github actions is a relatively new way of creating a workflows for your development cycle and it is gaining in popularity, especially since it has become a free feature for public repositories. It can be used to create CI/CD pipelines for a lot of different languages and infrastructure setups. Searching on the web we noticed that there are a lot of tutorialS about how to setup GitHub action that other people have built. But a lack of tutorials about how to build your own GitHub actions, and the ones that we found were quite basic. We would therefore like to make a tutorial explaining how to build a more complex CI GitHub action for …
=> How To Build Your Own Github Action

contributions/essay/settlin-joarek/README.md
We would like to learn more about A/B testing and its benefits.
=> Essay Proposal: A/B Testing and its benefits

contributions/covid19/perfah-joarek/README.md
=> Add link to repo (covid-19 proposal)

contributions/essay/davidjo2/README.md
David Johansson (davidjo2@kth.se)
I got introduced to the topic of monitoring during the week 5 presentation and thought it would be interesting to delve deeper into specifically website monitoring. Website monitoring plays a crucial role in, for instance, minimizing downtime and improving performance. I would like to learn about its importance and different key considerations to make in regard to the topic.
* Introduction
* Defining monitoring
* Relevance in a DevOps context
* Website Monitoring 
* Types of website monitoring
* Preventing downtime
* Improving performance
* Conclusions
* Key considerations
* https://www.manageengine.com/products/applications_manager/website-monitoring.html
* https://www.uptrends.com/what-is/website-monitoring
=> Essay proposal: Website monitoring overview

contributions/tutorial/emetha/README.md
**Members:** Emelie Tham (etham@kth.se)
1. What is BuildBot?
1. BuildBot vs other CI/CD Tools
2. What is Cypress.io?
1. Cypress.io vs Selenium
3. What is E2E testing?
1. E2E testing vs Unit testing
4. Installation instructions
5. BuildBot and Cypress set up instructions
7. Tests runs on the BuildBot and Cypress set up.
**Motivation:** I was interested in learning about how to apply CI/CD to my existing projects as well as using Cypress.io tool. In the Cypress documentation there was a page that showed how to set up continuous integration with Cypress and provided some examples on how to do so with popular CI/CD tools CircleCI, Jenkins and Travis CI. However, I did not see any on BuildBot. Upon searching the web there seemed to be no tutorials on this either.
=> Tutorial Proposal: E2E testing with Cypress.io and BuildBot

contributions/feedback-planning.md
Please provide feedback for the COVID-19 assignment.
=> Covid19: Help Fight Covid19 Social Web App: Feedback Requested

contributions/demo/varkalys-dautaras/README.md
Mindaugas Varkalys varkalys@kth.se @MindaugasVarkalys  
Justas Dautaras dautaras@kth.se @sonderangebot10
Deploying apps on Kubernetes cluster using Rancher pipelines
Rancher is a great tool which simplifies management of Kubernetes cluster through the intuitive UI.
It also has pipelines feature, which allows to run CI/CD jobs and see their status on the same UI environment. Having everything at the same place is a great benefit, so our demo will show the setup of Rancher pipelines as well as explain the main features of Rancher UI. As an example, we will demonstrate the continues deployment of a simple api to Kubernetes cluster using Rancher pipelines.
=> Demo proposal

contributions/essay/bratfors/README.md
- Robin Bråtfors (bratfors@kth.se)
I would like to learn more about Infrastructure as Code (IaC) and explore tools that achieve it through different means.
- What is IaC and what role does it have in DevOps
- What are configuration management and orchestration
- What are the differences between the two
- Explore two differing tools, probably Terraform and SaltStack
- Conclusion
=> Essay Proposal: Infrastructure as Code

contributions/tutorial/pojans-rug/README.md
| Name | Email |
| ------ | ------ |
| Pojan Shahrivar | pojans@kth.se |
| Richard Uggelberg | rug@kth.se |
We want to create an online tutorial which takes the user through the process of contributing to an open source project.
The aim is to expose the user to all of the git commands you need to know in a realistic scenario that tie them all together.
This tutorial is aimed at students that have experience with coding, but not necessarily has used version control to participate in development of a large project.
=> Tutorial Proposal: Version Control

contributions/feedback-planning.md
Demo feedback requested for https://github.com/KTH/devops-course/pull/470
Here is our final screencast https://youtu.be/fg2u2HVi08k.  Please choose Quality 1080 HD option in the youtube setting option to see it clearly.
=> Feedback Requested for Demo proposal: Virtual network peering in Microsoft Azure

contributions/essay/bwest-cwing/README.md
* Balthazar West, bwest@kth.se, Github: balwes
* Christer Winge, cwing@kth.se, Github: cwinge
What is penetration testing? Why use it? The essay will answer those questions and bring up various types of penetration testing. If time allows we will also discuss the available tools. The essay ends with a conclusion and references chapter.
The title is temporary
=> Essay proposal - Penetration testing

contributions/essay/felixlut/proposal.md
- Felix Luthman (felixlut@kth.se)
With the increased usage and complexity of web applications, i.e. applications that aren't installed on the user's machine, but rather deployed on a remote server, the microservice architecture has emerged as a solution to a lot of the problems a Monolithic web application may face. I would like to explore how these two models are structured, how they differ, and when one should pick one over the other.
* An introduction to what the Microservice architecture is, how it works, etc
* How it differs from the Monolithic approach
* A comparison of pros and cons between the two
- When one should be favored over the other
* Why this matters from a devops point of view
=> Essay Proposal: Microservice Architecture

contributions/tutorial/mhud/README.md
Added:
Here is the Wiki link for the complete tutorial: https://dev.azure.com/KthDevops/KthTutorial
Link to the website: https://kthtutorialweapp.azurewebsites.net/
=> Recreated Tutorial

contributions/demo/adambjo-mhud/README.md
**Members**
Helal Uddin (mhud@kth.se)
**Screencast Link**: https://youtu.be/o7DkXFiBHjk **(Please choose Quality 1080 HD option in the youtube setting option to see it clearly)**
**Description:**
According to Microsoft, Virtual network peering enables a seamless connection between Azure virtual networks. By using both private and global virtual network peering, it is possible to route traffic with low-latency, high-bandwidth. Virtual machines can communicate with other virtual machines by using VNP. This communication process is connected with other resources such as Azure subscription, Azure Active Directory(AAD) in the Azure portal. As this communication is private, there is no necessity to implement encryption. In this demo, we will present how to create …
=> Updated content

contributions/covid19/mhud-nsteele/README.md
Added source repo
added tech stack
added architecture model
Added link for the final report
=> Feedback completed

contributions/tutorial/chikafa-mjza-vemula/README.md
=> Finished tutorial: Testing Microservices in Spring Boot Applications: Tools and Techniques

contributions/feedback-planning.md
Requesting feedback for our tutorial on Testing Microservices in Spring Boot Applications: Tools and Techniques
=> Feedback for tutorial

contributions/tutorial/mhud/README.md
=> Revised Tutorial

contributions/repetition-planning.md
Updating the file to register our repeat for the presentation : An Introduction to Application-level Chaos Engineering and Its Tools
=> Updating for PR #673

contributions/essay/carljen-alevol/README.md
Related to https://github.com/KTH/devops-course/pull/676
=> Added link to finished essay

contributions/covid19/varkalys-dautaras/README.md
Mindaugas Varkalys varkalys@kth.se @MindaugasVarkalys  
Justas Dautaras dautaras@kth.se @sonderangebot10
Visualizing the places visited by infected people in Lithuania and matching them with Google Location history
Last month we participated in [HackTheCrisis](https://hackthecrisis.lt/) hackathon in Lithuania and together with other team members built a project to visualize previously visited places by the infected people. This data is provided by the Lithuanian government, but in very inconvenient format, so we visualized it on the map. We also created a feature to upload your Google Location history and see which infected places you visited. Apart from that, we worked with some epidemiologists and built a model, which calculates the likelihood of being infected depending on distance and …
=> COVID-19 project

contributions/demo/varkalys-dautaras/README.md
Add screencast and repository of the finished demo
=> Finished demo

contributions/demo/tommysam-stinalan/README.md
Link to the deployed [demo](https://dd2482-demo-data-corruption.firebaseapp.com/)
=> Demo Submission: Data Corruption

contributions/covid19/varkalys-dautaras/README.md
I added links to the finished project
=> COVID-19: Finished project

contributions/tutorial/ruwaid-davidjo2/README.md
Ruwaid Louis - ruwaid@kth.se @ruwaid4 </br>
David Johansson - davidjo2@kth.se @SoFoDa
This tutorial is about how to use the tool Rodin to model a system in Event B. The tutorial goes through needed theory, proof obligations, some lesser known operators and model development. How to install Rodin is also included in the tutorial. We end the tutorial with an example of modelling a system.
https://medium.com/@ruwaid4/rodin-modelling-with-event-b-8fdab6c65003
=> Completed tutorial - Rodin: Modelling with Event-B

contributions/essay/pojans-sraa/README.md
Added link to finished essay in README.md
https://medium.com/@pojanshahrivar/what-is-continuous-testing-1d6a40439382?sk=9b4a17997204fcc9771288954c630d4e
=> Add link to finished essay in README.md

contributions/tutorial/alevol-keivanm/READEME.md
We ended up shifting the topic of the tutorial just a bit, so we changed the README.md description as well. The topic is still however about GitHub actions.
=> Finished Tutorial: Link added

contributions/demo/jadlers/README.md
I've added links to the demo on YouTube as well as a link to the project repository on GitHub.
> ## Screencast link
> 
> [https://youtu.be/yPdwBRndwPY](https://youtu.be/yPdwBRndwPY)
> 
> ## Project repository
> 
> The repository can be found [here](https://github.com/jadlers/bollsvenskan-api).
=> Demo submission jadlers

contributions/demo/pojans-akshays/README.md
The screencast has been made available on [youtube](https://youtu.be/AO7T9LJGoGc). Enable the CC option to get subtitles.
There is an easter egg in the screencast that should be visible to the perceptive person, but in case you've missed it. Pause the video around 2 minutes and 20 secs and take a look in the left side.
To "Unlock the secrets of longevity", please visit [http://35.228.240.95:3000/](http://35.228.240.95:3000/) and have a go.
=> Demo: Add youtube link

contributions/demo/akhily/Readme.md
Updated Readme with link to URL.
=> Completed Demo: Using Terraform with GCP server for static IP webhook calls

contributions/demo/johvh-davidjo2/README.md
**Youtube**: https://www.youtube.com/watch?v=Gc8SlsqPp-c
Subtitles can be enabled by clicking the subtitles button on youtube.
**Github**: https://github.com/JohanKJIP/ci-cd-demo
Johan von Hacht (johvh@kth.se)
David Johansson (davidjo2@kth.se)
Demo of a CI/CD pipeline using Github actions.
We have implemented a CI/CD pipeline for a small website using Docker and Github actions. The demo shows how the pipeline works in action. 
We also provide the viewers with a take-home message. The repository is also available on Github so that the viewer can fork it if they want to experiment with the pipeline.
=> Add final demo: CI/CD pipeline using Docker and Github actions

contributions/demo/sunneg/README.md
Copy of addition to README:
Here is the link to my demo for the demo day: https://www.youtube.com/watch?v=5IkDrgFSFw4&t=7s The accompanying GitLab repository: https://gitlab.com/christinasunnegardh/devops-gitlab-demo
=> Finished demo: GitLab CI/CD pipeline (Building, Testing, deployment to Heroku)

contributions/demo/mjza-chikafa-nagavem/Readme.md
Finished the demo video and posted the link.
=> Posted the video Link

contributions/demo/javierro-hiteshs/README.md
Signed-off-by: Javier Ron <javierron90@gmail.com>
=> Demo submission for May 5th feedback session

contributions/demo/htchan-mgabri/README.MD
Added link to the repo for material used during the demo and relation to devops, after feedback
=> Demo Update: Deploying an online storage system on Microsoft Azure

contributions/demo/cwing/README.md
Updated screencast based on feedback.
=> Final demo screencast submission

contributions/demo/joarek-settlin/README.md
Updated the demo according to feedback in pull request 606
=> Update from feedback

contributions/demo/pojans-akshays/README.md
The screencast has been made available on [youtube](https://www.youtube.com/watch?v=7JW9118abpU). Enable the CC option to get subtitles.
**Audio:** Increased bit rate from 128 to 192 kbps
**Audio:** Rerecorded parts to increase overall quality
**Slides:** Changed text on slide 2,3 and take away slide to better spoken word
**Video:** Increased resolution to 1080p
**Script:** Changed deployment.yaml segment to include live coding
=> Demo: final turn in

contributions/demo/jonasjo5-marcusew/README.md
Updated demo with the given feedback in mind.
=> Updated demo

contributions/demo/mjza-chikafa-vemula/Readme.md
Updated the demo link with the suggested changes for the final submission
=> Updated Video Link-Final Submit

contributions/demo/madon-vals/README.md
Here is the last version of our demo (new Youtube link), taking into account all the feedback received.
Thank you to all the reviewers :+1: !!
=> demo feedback: new link for madon-vals terraform demo

contributions/demo/javierro-hiteshs/README.md
In the latest version we enhanced our demo with the feedback provided by or classmates, such changes include:
- Reduced total video duration to less than 5 minutes
- Music volume lowered.
- Faster and clearer introduction.
- Clearer take-home message.
- Explanin previously unaddressed reference to Minikube
- Used arrows in-video to better direct viewer's attention
- Katacoda tutorial expanded.
Signed-off-by: Javier Ron <javierron90@gmail.com>
=> Update demo link and address feedback for demo task

contributions/demo/adambjo-mhud/README.md
Helal Uddin (mhud@kth.se)
Virtual Network Peering with Microsoft Azure and Terraform
https://youtu.be/WPZPVX2ptF0
https://github.com/adbjo/devops-demo
According to Microsoft, Virtual Network Peering enables a seamless connection between Azure virtual networks. By using both private and global virtual network peering, it is possible to route traffic with low-latency, high-bandwidth. Virtual machines can communicate with other virtual machines by using VNP. This communication process is connected with other resources such as Azure subscription, Azure Active Directory(AAD) in the Azure portal. As this communication is private, there is no necessity to implement encryption. With Terraform, deployment of such infrasctructures can be easily automated in code.
In …
=> Final demo submission after feedback

contributions/demo/almajni-rezkalla/README.md
* Nour Alhuda Almajni - almajni@kth.se - @nour95
* George Rezkalla - rezkalla@kth.se - @georgewbar
https://youtu.be/3OUkpIv2a7Q
https://github.com/demo-cicd-k8s/datetimeserver_demo_cicd_kubernetes
We will create an End-to-End CI/CD pipeline with Continuous Deployment (Zero-Downtime Deployment) using Jenkins, Ansible and Kubernetes `Minikube`. The deployed application will be a Java application that shows the current Date and Time together with the current version of the application to show that a new version of the application was deployed with Zero-downtime.
To be more concrete, we will create a **local** cluster consisting of one node in a virtual machine on a macOS laptop using `Minikube`. Moreover, we  will use `Kubectl` to show debugging information. Then, we will create a pipeline …
=> Final Demo Submission: End-to-End CI/CD (Continuous Deployment) pipeline with Jenkins, ansible, and Kubernetes `Minikube`

contributions/covid19/tommysam-jii/COVID19_COURSE_INFO.md
We had a minor bug in our report, where the path for some of the images were wrong. We have mention this in a comment in our previous PR #739. Got an OK to fix this from the TA:s.
=> fix: Minor bug in our COVID19 report

contributions/tutorial/hiteshs-eyueltb-avijit/README.md
Updating readme for Tutorial as per suggestions in today's lecture.
=> tutorial: Update README.md

contributions/covid19/varkalys-dautaras/README.md
We added the detailed description about our contribution to COVID-19 project because our contribution information was lost when the project became open sourced.
=> Add description about the contribution to COVID-19 project

contributions/presentation/week3/vemula-akhily/Readme.md
Published an article on medium in addition to the presentation. Posting the same for reference,it can be a useful and interesting read.
=> Added Link to  Article on Topic

contributions/repetition-planning.md
Updating the file to register our repeat for the presentation : Automation test using selenium framework
=> Presentation repetition PR# 462

contributions/tutorial/vals/README.md
I have updated my tutorial according to the feedback provided.
Changes made:
* Added new Overview and Background sections giving the tutorial a better focus and giving the reader more information about the technologies used.
* Removed comments from the dockerfile and explained them separately.
* Changed port from 80 to 8080
* Added reference links to documentation where needed
* Added 2 Fun Facts
* Added a summary section
* general improvements in the instructions
=> final tutorial submission

contributions/open-source/hmellin-paulher/README.md
Paul Löwenström: paulher@kth.se
Henrik Mellin: hmellin@kth.se
Zerocode introduction video
We would like to contribute to an open-source project, namely https://github.com/authorjapps/zerocode.
The project has an issue where they want a short video demonstration of Zerocode. 
We think this contribution would be appreciated as the issue is labeled as _help wanted_.
This contribution could also improve the documentation of the project in a way, as it will 
help new users get familiar to Zerocode. 
The issue can be found here:
https://github.com/authorjapps/zerocode/issues/231
Since this Zerocode is about API automation and testing frameworks, 
we think this contribution falls under this topic:
https://github.com/KTH/devops-course/issues/9
Video link: …
=> Task repetition, Open-source contribution. Zerocode Introduction Video.

contributions/demo/akhily/Readme.md
Addressed all the suggestions provided in feedback.
=> add link to final version of screencast

README.md
added a short description of fip, with a few references. what do you think?
=> doc: acknowledge FIP

contributions/demo/dleon-nicolaih/README.md
Diego Leon (dleon@kth.se)  
Nicolai Hellesnes (nicolaih@kth.se)
This demo focuses on the deployment part of CI/CD. Specifically, automatic deployment. To demonstrate this, a proof of concept web app that can perform division was created and used with our CI/CD pipeline. This application was deployed in a Kubernetes cluster running on Google Kubernetes Engine.
Here is a list of the criteria we want to fulfill:
* The demonstration screencast is clearly motivated (why it matters for Devops?) 
- **Motivation**: the demo is clearly motivated at minute 0:30.
* The demonstration screencast is sublime (eg visually appealing) 
- **Motivation**: There is not to much text and background has been added to differentiate the text from the video. Apart from that, white-colored boxes are used to help the …
=> Final demo submission after repeat

contributions/essay/pojans-sraa/README.md
**Title:** Changed title to better reflect on the content of the essay.
**Intro:** Reduced length and focused more on learning outcomes and content of essay.
**References:** Adopted an in-line referencing style with links.
**Methods:** Added penetration testing, linked to all methods.
**Methods & Tools:** Added discussion about which methods and tools and the  criteria for selection.
**Conclusion:** Rewritten to reflect the on all points that have been brought up in the essay & tie the knot together.
**Comments:** We decided to keep the references in the end, even though, we prefer to remove them to better fit in medium. We did this because we want to be 100% sure that the references criteria has been met. We have now used two styles of referencing which should satisfactory. We feel like …
=> Updateate README.md

contributions/covid19/mgabri-nicolaih/README.md, contributions/essay/mgabri/README.md
The essay is available on the medium link provided in the README and as a PDF
=> COVID sub and PDF of Eassy
