KTH/devops-course

contributions/presentation/T1G88/README.md
Anders Sjöbom asjobom@kth.se
Valtteri Lehtinen vleh@kth.se
We would like to to do a presentation about the Open Container Initiative.
It's an organization founded by Docker, CoreOS and other leaders in the container industry to create a formal standard for containers.
www.opencontainers.org.
We would like to present on the 1 of april since that lecture aligns with the topic.
=> presentation OCI

contributions/demo/hors-yptu/README.md, contributions/demo/hors_yptu/README.md
Group member:
Stephan Horsthemke (hors@kth.se)
Yi-Pei Tu (yptu@kth.se)
In this demo, we want to use kubernetes on AWS(https://aws.amazon.com/eks/) to design a CI/CD pipeline.
This pipeline connects to git repositories, tests automatically and builds new images in case of successful tests. New images are automatically deployed in the cluster. Ultimately we want to have a setup in which we only push a change to the master of the repository and, in case the code is alright, the new version will automatically run in the cluster.
To reach this we want to first evaluate some CI/CD tools like travis(https://travis-ci.org/) and circleCI (https://circleci.com/) to then create the demo with our favorite solution.
source:
https://kubernetes.io/docs/setup/turnkey/aws/
https://kubernetes.io/
=> Demo: CI/CD pipeline with automatic deployment

contributions/open/jcroona-slarse/README.md
Hello! @jcroona and I have finished a fully functioning prototype for our labeling bot. We don't have a public GitHub App running at it this time, as we're only on the free tier of AWS Lambda, but you can try it out in the demo repo linked in the README (for which there is a private GitHub app installed, running Labelbot).
There are instructions for how to deploy it as a private GitHub app in the [documentation](https://labelbot.readthedocs.io). See the README here and in the Labelbot repo for further details!
Please let us know if there's something we should fix, or if you'd like us to help deploy it for the course repo.
=> [open] Labelbot project submission

contributions/demo/erikjo9/README.md
I intend to demonstrate configuring Jenkins to launch it's own build agents on Amazon Web Services.
Since the configuration is minimal I also intend to show a use case were such a solution will avoid resource
starvation in an environment where there are many developers and many concurrent builds.
This solution saves both time and money since build agents are launched and destroyed on-demand, so it is very relevant
to DevOps.
=> Dynamic jenkins build agents on AWS (demo)

contributions/open/erikjo9/README.md
The [slack notification plugin](https://github.com/jenkinsci/slack-plugin) is a Jenkins plugin that allows sending
build notifications to slack. It supports traditional "free style" build project as well as pipelines, however the
functionality is very limited when used in pipelines.
When using the plugin in a free style project the notifications may include information like build status (pass/fail/etc), test results and commits. But when using the "slackSend" step supported in pipelines you are only able to send messages that you have to format yourself using much knowledge about the slack API.
I intend to create a prototype improvement to the plugin by adding a new pipeline step called "slackNotify" that has support for build information like the plugin has for free style projects. I do …
=> Improving slack notification plugin for Jenkins (Open)

contributions/open/aeri3-egedda/README.md
The goal of our open assignment was to contribute to open-source JSON-libraries. The issue we created as a result of our open assignment has now been resolved with our bug-causing JSON-input added as test cases to the project. As such, we would like this to show in our README even if it happened after the submission deadline.
=> Open assignment update

contributions/tutorial/jonasjo5/README.md
Jonas Johansson, jonasjo5@kth.se
A step-by-step tutorial on how to setup and use a code coverage tool on your Github repository and integrate it with your CI solution. As an example I would suggest covering how to setup a Python or Java/maven project with Codecov or Coveralls. Each solution of course already have some documentation but I have yet to find a tutorial that is thorough and goes through all the steps mentioned below: 
Suggestions:
- A small introduction to code coverage.
- A comparison between existing solutions and a motivation of how the solution covered by the tutorial was chosen.
- Prepare the repository (if necessary).
- Setup the code coverage tool.
- Integrate the tool with your repository.
- Integrate the tool with a CI solution.
- A few examples on how to use the …
=> Tutorial suggestion: Code Coverage

contributions/open-source/jadlers-carljen/README.md
- Jacob Adlers (jadlers@kth.se)
- Carl Jensen (carljen@kth.se)
Develop an integration for Home Assistant to get information from a Jenkins
CI/CD server.
This integration would make it possible for users of the home automation system
Home Assistant to get information about pipelines. Information we would like to
include is some of the following:
- Job-status (success/failed)
- Execution time
- Link to the build and/or commit on git
- Branch
- Time of execution
This would allow end-users of the integration to create automations, for
example, to announce a failing build on speakers around their home or set the
colour of a lamp based on events from their Jenkins server.
We're planning to use the Generic Webhook trigger plugin that is supported in
Jenkins. This might however not be the final …
=> Open source: Jenkins integration for Home Assistant

contributions/covid19/tommysam-jii/README.md
**COVID19 Proposal**
**Members**
Tommy Samuelsson (tommysam@kth.se)
Johanna Iivanainen (jii@kth.se)
**Topic**
COVID19 info for KTH-data Student
The idéa is to provide a student on KTH with relevant information about changes in courses that are caused by the COVID19 precautions. We will do this by creating a web-app that students can access and se what changes has been made course by course. 
Three example for tabs / course folders:
**DD2482**
Course information is only available on github. The course no longer has any live lectures. They are only on Zoom, labs is also held on Zoom.
**SF1923/SF1924**
This course has no longer any live lectures, only on Hangouts. The partial exam has NOT been canceled. Instead, it will be held on Canvas.
**DD1368**
The re-exam has not been canceled, but has …
=> Add initial COVID19 Proposal: COVID19 info for KTH-data Student

contributions/open-source/ruwaid-dstevens/README.md
Ruwaid Louis (ruwaid@kth.se)
GitHub: @ruwaid4
David Stevens (dstevens@kth.se)
Github: @stevensdavid
Create a new rule for Wemake Python Styleguide along with all of the required tests and get it approved by the maintainer.
GitHub Repo: https://github.com/wemake-services/wemake-python-styleguide
Wemake Python Styleguide strives to be the strictest linter ever. It has an active community in GitHub and is very popular. It is essentially a flake8 plugin making it very easy to use for anyone wanting to put themselves in agony.
=> Open-source proposal: Wemake Python Styleguide

contributions/tutorial/jadlers-xmas92/README.md
- Jacob Adlers (jadlers@kth.se)
- Axel Boldt-Christmas (axelbc@kth.se) 
- Github username: xmas92
GitHub has created the ProBot app in order to make it easy to build a bot connected to your repositories. This feature is not available on Gitlabs and it requires more setup and manual work to get a bot set up. We’ll create a tutorial on katacoda which guides you through the steps necessary to start building your own bot.
Preliminary outline:
1. Create a bot account in self-hosted GitLab.
2. Configure bot permissions and webhooks for repository
3. Create simple bot software using API framework GitBeaker
4. Explore bot <-> GitLab interactions.
Bots can help to automate repetitive tasks in a repository. There are a huge amount of bots created for GitHub and the reason is most likely that it’s …
=> Tutorial proposal: Creating a bot on GitLab

contributions/open-source/perfah-applelid/README.md, contributions/open-source/perfah/README.md
1. Per Fahlander (perfah@kth.se)
2. Gunnar Applelid (applelid@kth.se)
Patch the crate [wlroots-sys](https://github.com/swaywm/wlroots-rs/tree/master/wlroots-sys) belonging to the deprecated [wlroots-rs](https://github.com/swaywm/wlroots-rs) (rust bindings for [wlroots](https://github.com/swaywm/wlroots)) library to suit it for use in other projects directly.
A new crate would preferably be published on a separate GitHub repository, although a fork+merge request could also work. The original author would of course be given full credit regardless. 
I think a new repo would be better since I only want to keep the wlroots-sys part of the repo.
Some suggestions for tangible changes to the crate: 
- Make sure that the automatic building work in an self-contained manner as much as possible
- …
=> Open-source proposal: Patching wlroots-sys

contributions/tutorial/jovi/README.md
Johan Vikström, jovi@kth.se
Step-by-step tutorial on how to configure and deploy kube-monkey (https://github.com/asobti/kube-monkey) to use chaos engineering to ensure reliability of services.
This will cover deploying kube-monkey manually outside of kube-system (the namespace that has all internal kubernetes system deployments), how to switch configs and finally how to read the logs and make sure it actually works and kills pods.
There are tutorials on how to deploy kube-monkey online, however they aren't very thorough. All of them also deploy to kube-system which is a massive security issue (you basically give kube-monkey admin access to the cluster).
I'm planning on creating this on kataconda and provide a small test-environment deployed on minikube.
Rough outline:
* What is …
=> Tutorial proposal: Chaos engineering in kubernetes clusters

contributions/open-source/adambjo-bratfors/README.md
GitHub: adbjo
Robin Bråtfors (bratfors@kth.se)
GitHub: rbratfors
Migrate the [Strongbox documentation](https://strongbox.github.io/) to Material for MkDocs 5.
Solves this issue: https://github.com/strongbox/strongbox/issues/1715 
The following tasks will need to be carried out:
- Upgrade docker image so it uses the latest version ci-build-images/images/mkdocs/Dockerfile.mkdocs and installs the correct pip dependencies
- Make any necessary configuration changes
- Add support pymdownx.tabbed in markdown_extensions under mkdocs.yaml (this requires pymdown-extensions>=7.0)
- Search for todo: pymdownx.tabbed within the project to
- Strongbox is an **artifact repository** manager
- Docker image configuration (**containerization**)
- MkDocs is a **project …
=> Open-source proposal: Upgrade Strongbox documentation to mkdocs-material-5.0.0

contributions/demo/bratfors-kasperli/README.md
Robin Bråtfors (bratfors@kth.se)
Kasper Liu (kasperli@kth.se)
Demo of using Calico policies in Kubernetes
Calico is used for network security and source networking for containers and virtual machines. We want to demonstrate how Calico policies can be used in Kubernetes.
=> Demo proposal: Calico policies in Kubernetes

contributions/demo/bratfors-kasperli/README.md
Initially we wanted to perform the demo locally, but we decided to switch to GKE instead for the reasons stated in the README file.
This is an update of a prior pull request (#605).
Kasper did an essay on cloud, and the technology is featured in this demo (Google Cloud Platform) but the focus will be on container orchestration (Kubernetes and Calico) so we feel that they don't clash.
=> Updated demo proposal: Calico policies in Kubernetes

contributions/open-source/ruwaid-dstevens/README.md
Ruwaid Louis (ruwaid@kth.se) </br>
GitHub: @ruwaid4
David Stevens (dstevens@kth.se) </br>
Github: @stevensdavid
Create a new rule for Wemake Python Styleguide along with all of the required tests and get it approved by the maintainer. </br>
GitHub Repo: https://github.com/wemake-services/wemake-python-styleguide
Wemake Python Styleguide strives to be the strictest linter ever. It has an active community in GitHub and is very popular. It is essentially a flake8 plugin making it very easy to use for anyone wanting to put themselves in agony.
The [PR](https://github.com/wemake-services/wemake-python-styleguide/pull/1315) has been accepted and will eventually be merged in the next version.
=> Completed open-source: Wemake Python Styleguide

contributions/demo/madon-vals/README.md
Victor Josephson (vals@kth.se).
Github username: valsen
Maël Madon (madon@kth.se).
Github username: Mema5
Use Terraform to setup and run a Google Compute Instance.
=> Demo Proposal: Setting up a Google Compute instance with Terraform

contributions/demo/cwing/README.md
Just as a short background, I figured I'd give the reason I thought of doing this demo.
While working on a tutorial, we used Katacoda, as it is a simple way to have others be able to perform the same task without a local environment.
It also provides an extremely easy way to reset your whole environment. During the time of us working with Katacoda, we however ran into some problems with the service.
When using the Python playground, we would often get the wrong type of environment, so instead of getting a Python environment we would get some other type.
Often a Docker or Jupyter environment. At the beginning we didn't know about this issue, or notice it, this meant time was spent using old versions of Python and Pip which was not ideal.
The title needs to be worked on, not too easy to …
=> Demo proposal - Publishing your own customized terminal environment by deploying a simple website on AWS

contributions/covid19/vals/README.md
https://github.com/valsen/covid19
Victor Josephson (vals@kth.se).
Github username: valsen
A single-page website that displays a chart overlaying coronavirus related google search trends on top of daily new reported cases of COVID-19. A dropdown selector lets the user choose either the United States or Sweden, meaning the google trends and covid cases are local for that country. A text input field lets the user choose up to 5 comma-separated search terms for the google trends.
Data is fetched from Google Trends, covidtracking.com and covid-api.com.
Many websites offer detailed data and charts on the coronavirus pandemic, but my website adds an interesting visual as it shows a timeline of the search trends of COVID-19 symptoms on top of the reported cases. A spike in the search trends might …
=> Covid19 proposal: Visualizing daily new cases (USA/Sweden) along with Google Trends

contributions/demo/cwing/README.md
Updated with demo URLs
Screencast URL with easter egg hint: https://youtu.be/VHttX3IZOhw (might be hard to spot due to speed up)
Screencast URL with easter egg shown: https://youtu.be/XTmD-rRdCK4
Github repo: https://github.com/cwinge/web-terminal
URL to the demo will be posted on the 5th as a comment on the pull request. The easter egg can be used with the demo.
=> Added demo URLs

contributions/demo/sunneg/README.md
Copy of edits to README:
Link to the Youtube screencast: https://youtu.be/0YTg6ryIxOE
The accompanying GitLab repository: https://gitlab.com/christinasunnegardh/devops-gitlab-demo
The improvements that have been made after the feedback on the Demo Day are the following:
- Added a description to the README at the accompanying GitLab repository
- Fixed minor issues with the subtitles
- Removed the "prerequisites" part in the screencase and updated the description with this information instead
- Removed the unnessecary action in the screencast where ruby is installed altought we are already on a Ruby Docker image.
- Added information about that you can specify a specific version of the image in docker
- Changed the easter egg completely
- Major changes to the end/take-away part in the …
=> Updated demo (after feedback): GitLab CI/CD pipeline (Building, Testing, Deployment to Heroku)

contributions/demo/jadlers/README.md
It was not possible to do the changes pointed out by reviewers (#809) in YouTube-studio for the link to stay the same. I've therefore uploaded a new version and updated the link.
> ## Screencast link
>
> [https://youtu.be/BX7Fa_DdlQc](https://youtu.be/BX7Fa_DdlQc)
=> Update YouTube link for jadlers monitoring demo

contributions/tutorial/bratfors-kasperli/README.md
- Robin Bråtfors, bratfors@kth.se
- Kasper Liu, kasperli@kth.se
A tutorial that teaches the reader how to install and setup TeamCity from scratch for a gradle project on GitHub. The tutorial will have some screen captures and should be easy to understand for anyone with experience in GitHub, but not necessarily with continuous integration.
The tutorial is posted on:
https://github.com/Kappenn/TeamCity_Tutorial
We have a fun fact in the background section and also an easter egg if one chooses to use the provided repo for the tutorial.
We have removed the tutorial from Medium and now it exist only on github.
We have expanded the background to explain about how CI and automated build tools are connected to Devops and why TeamCity is a good option.
We have added instructions to install Java 8 …
=> Repeat Tutorial Complete

contributions/course-automation/zidi-sihan/README.md
Chen, Zidi: zidi@kth.se, https://github.com/Chen-Zidi
Chen, Sihan sihanc@kth.se, https://github.com/Spycsh
We want to check the validity of the deadlinks in the course github 
text descriptions, for example, readme files. Because sometimes 
the links might be not accessible or out of date.
TODO
=> Course Automation: Checking link validity in the course github text descriptions
